# NumPy

Numpy atau Numerical Python adalah sebuah package yang digunakan untuk manipulasi data tipe numerik.

Banyak fungsi matematik, formula, yang basic, dipermudah oleh package Numpy.

Banyak package yang lebih complex seperti package statistics scipy stats atau untuk manipulasi data tabular pandas yang dibangun di atas package NumPy ini.

Tujuan:
- lebih familiar dengan package python
- struktur data n-dimensional array yang ada di dalam numpy
- belajar cara pakai package numpy untuk manipulasi angka

## NumPy Array
kita bisa konversi list berisi angka menjadi sebuah NumPy Array. Ada beberapa requirement:
1. isinya harus angka semua, boleh float boleh int
2. kalau dimensi lebih dari 1, setiap dimensi memiliki ukuran yang sama

In [ ]:
import numpy as np

In [ ]:
# Create Array
np.array([1,2,3])

array([1, 2, 3])

kenapa pakai numpy array dan bukan list? ada banyak teknik yang built-in di dalam numpy array yang mempermudah kita handle data numerik

In [ ]:
stok = np.array([10,20,15])
harga= np.array([5000,25000,51000])

stok * harga

array([ 50000, 500000, 765000])

In [ ]:
stok + np.array([10,10,10])

array([20, 30, 25])

In [ ]:
stok + 10

array([20, 30, 25])

In [ ]:
# Create Array - generate list angka langsung tanpa konversi dari list/tuple
# isinya 0 semua
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
# isinya 1 semua
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# isinya angka urut
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(5,50)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
np.arange(5,100,10)

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

# Array 2D
NumPy Array bisa memiliki lebih dari 1 dimensi

In [ ]:
np.array([[1,2,3]])

array([[1, 2, 3]])

diatas adalah numpy array 2 dimensi dengan 1 row dan 3 columns

In [ ]:
np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

diatas adalah numpy array 2 dimensi dengan 4 row dan 3 column

## Shape
untuk mengecek sebuah numpy array memiliki:
- berapa dimensi
- berapa item (ada berapa angka totalnya)
- berapa row, column... berapa item per dimensi

kita bisa gunakan `shape`

In [ ]:
contoh_arr = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])

contoh_arr.shape

(4, 3)

di contoh diatas, numpy array kita yang memiliki 4 rows dan 3 columns, memiliki shape `4,3`

artinya, di dimensi pertama ada 4 item. di dimensi kedua ada 3 item.

row adalah dimensi pertama, column adalah dimensi kedua.

In [ ]:
contoh_arr = np.array([7,8,9])

contoh_arr.shape

(3,)

di contoh diatas, numpy array kita memiliki 1 dimensi berisi 3 item. jadi shape nya `3`

In [ ]:
contoh_arr = np.array([[7,8,9]])

contoh_arr.shape

(1, 3)

di contoh diatas, dimensi pertama memiliki 1 item saja. 1 row. dimensi kedua memiliki 3 item. 3 column.

In [ ]:
np.array([[7],[8],[9]])

array([[7],
       [8],
       [9]])

In [ ]:
contoh_arr = np.array([[7],[8],[9]])

contoh_arr.shape

(3, 1)

## recap
- numpy array bisa memiliki lebih dari 1 dimensi
- kita buat numpy array menggunakan:
  - np.array()
  - np.ones()
  - np.zeros()
  - np.arange()
- untuk mengecek bentuk sebuah numpy array kita gunakan `shape`

untuk mengubah `shape` sebuah numpy array kita bisa gunakan `reshape` dan teknik lainnya seperti: append, delete, dan sort.

## Mengubah Numpy Array - reshape

kita bisa membuat numpy array dengan np.ones, zeros, dan arange. tapi bentuknya semua 1 dimensi. untuk membuat yang bentuknya 2 dimensi kita pakai `reshape`

In [ ]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones(12).reshape((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.ones(12).reshape((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.ones(12).reshape((2,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
np.ones(12).reshape((1,12))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

dengan menggunakan reshape dan memberi shape seperti (1,12) atau (3,4) kita mengubah shape numpy array menjadi 2 dimensi

note: untuk ones dan zeros shape nya bisa kita langsung request tanpa menggunakan reshape

In [ ]:
np.ones((6))

array([1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones((6,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

perhatikan shape (6) membuat 1 dimensi. dan shape (6,3) membuat 2 dimensi.

untuk np.arange, khusus kita bisa pakai reshape saja, untuk mengubah bentuk dan dimensi nya

In [ ]:
np.arange(12).reshape((3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

contoh diatas, kita membuat numpy array 2 dimensi dengan 12 angka urut bentuk 3 row 4 column

sebenarnya dengan menggabungkan beberapa kemampuan numpy array kita bisa "generate" data dummy dengan mudah. contohnya hasil lempar dadu, result antara 1-6, kita bisa buat dummy data hasil lempar 100x.

In [ ]:
# np.random.random -- untuk membuat data random
np.random.random(10)

array([0.61654614, 0.98022031, 0.03185836, 0.85224338, 0.51867221,
       0.83643745, 0.18181928, 0.81818816, 0.7297825 , 0.43899211])

In [ ]:
np.random.random(10) * 6

array([3.44547367, 4.19725603, 0.75589464, 0.85848698, 3.36854271,
       5.27140438, 4.57688912, 2.71440659, 4.4869498 , 2.66390181])

In [ ]:
# ubah jadi integer
random_arr = np.random.random(100) * 6 + 1
random_arr.astype(int)

array([6, 3, 5, 3, 2, 3, 6, 3, 1, 6, 1, 3, 6, 2, 6, 1, 4, 3, 3, 6, 6, 1,
       3, 5, 5, 5, 2, 2, 4, 5, 5, 5, 4, 2, 5, 4, 3, 5, 2, 4, 1, 2, 1, 1,
       3, 6, 5, 2, 2, 2, 1, 5, 1, 3, 5, 1, 1, 1, 2, 2, 4, 2, 6, 5, 4, 1,
       1, 6, 3, 3, 3, 6, 5, 3, 1, 5, 5, 6, 1, 6, 2, 5, 5, 6, 6, 3, 6, 4,
       6, 3, 1, 3, 5, 1, 3, 2, 1, 6, 5, 3])

In [ ]:
# reshape, misalnya ini hasil lempar dadu 5 orang, masing2 melempar 20x. jadi kita bentuk menjadi 5 baris 20 kolom
random_arr = random_arr.astype(int)
random_arr.reshape((5, 20))

array([[6, 3, 5, 3, 2, 3, 6, 3, 1, 6, 1, 3, 6, 2, 6, 1, 4, 3, 3, 6],
       [6, 1, 3, 5, 5, 5, 2, 2, 4, 5, 5, 5, 4, 2, 5, 4, 3, 5, 2, 4],
       [1, 2, 1, 1, 3, 6, 5, 2, 2, 2, 1, 5, 1, 3, 5, 1, 1, 1, 2, 2],
       [4, 2, 6, 5, 4, 1, 1, 6, 3, 3, 3, 6, 5, 3, 1, 5, 5, 6, 1, 6],
       [2, 5, 5, 6, 6, 3, 6, 4, 6, 3, 1, 3, 5, 1, 3, 2, 1, 6, 5, 3]])

## append, delete, sort
append untuk menambahkan value

delete menghapus

sort mensortir hingga angka dalam numpy array urut

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

c = np.append(a,b)
c

array([1, 2, 3, 4, 5, 6])

In [ ]:
a = np.array([[1,2,3]])
b = np.array([[4,5,6], [7,8,9]])

c = np.append(a,b)
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# hapus angka 9 di array c
np.delete(c, -1)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
# sort
random_arr

array([6, 3, 5, 3, 2, 3, 6, 3, 1, 6, 1, 3, 6, 2, 6, 1, 4, 3, 3, 6, 6, 1,
       3, 5, 5, 5, 2, 2, 4, 5, 5, 5, 4, 2, 5, 4, 3, 5, 2, 4, 1, 2, 1, 1,
       3, 6, 5, 2, 2, 2, 1, 5, 1, 3, 5, 1, 1, 1, 2, 2, 4, 2, 6, 5, 4, 1,
       1, 6, 3, 3, 3, 6, 5, 3, 1, 5, 5, 6, 1, 6, 2, 5, 5, 6, 6, 3, 6, 4,
       6, 3, 1, 3, 5, 1, 3, 2, 1, 6, 5, 3])

In [ ]:
np.sort(random_arr)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

ndim dan size

In [ ]:
random_arr.ndim

1

In [ ]:
random_arr.size

100

In [ ]:
random_arr.shape

(100,)

selain `shape` kita bisa gunakan `ndim` untuk cek ada berapa dimensi dan `size` untuk mengetahui ada berapa angka di dalam sebuah numpy array

In [ ]:
arr2 = random_arr.reshape((5,20))

print(arr2.ndim, arr2.size, arr2.shape)

2 100 (5, 20)


In [ ]:
arr2

array([[6, 3, 5, 3, 2, 3, 6, 3, 1, 6, 1, 3, 6, 2, 6, 1, 4, 3, 3, 6],
       [6, 1, 3, 5, 5, 5, 2, 2, 4, 5, 5, 5, 4, 2, 5, 4, 3, 5, 2, 4],
       [1, 2, 1, 1, 3, 6, 5, 2, 2, 2, 1, 5, 1, 3, 5, 1, 1, 1, 2, 2],
       [4, 2, 6, 5, 4, 1, 1, 6, 3, 3, 3, 6, 5, 3, 1, 5, 5, 6, 1, 6],
       [2, 5, 5, 6, 6, 3, 6, 4, 6, 3, 1, 3, 5, 1, 3, 2, 1, 6, 5, 3]])

# Indexing dan Slicing
Indexing - mengambil 1 data dari sebuah numpy array

Slicing - mengambil beberapa data sekaligus dari sebuah numpy array

In [ ]:
# kita gunakan contoh array baru
arr3 = np.arange(7,108,7).reshape((3,5))
arr3

array([[  7,  14,  21,  28,  35],
       [ 42,  49,  56,  63,  70],
       [ 77,  84,  91,  98, 105]])

mau ambil angka 49, kita gunakan indexing. berapa index angka 49?

angka 49 ada di baris ke-2 dan di kolom ke-2

baris ke-2 memiliki index 1 di dimensi pertama

kolom ke-2 memiliki index 1 di dimensi kedua

jadi, index yang kita perlukan adalah [1,1]

In [ ]:
arr3[1,1]

49

mau ambil angka 84, kita gunakan indexing, berapa index angka 84?

angka 84 ada di baris ke-3 dan di kolom ke-2

baris ke-3 memiliki index 2 di dimensi pertama

kolom ke-2 memiliki index 1 di dimensi kedua

jadi, index yang kita perlukan adalah [2,1]

In [ ]:
arr3[2,1]

84

In [ ]:
arr3

array([[  7,  14,  21,  28,  35],
       [ 42,  49,  56,  63,  70],
       [ 77,  84,  91,  98, 105]])

untuk mengambil banyak angka sekaligus, kita gunakan slicing. misalkan kita anggap data arr3 adalah data 3 orang berbeda: andi budi cindy. kita mau ambil data milik andi dan budi - baris pertama dan kedua saja.

berarti kita mau ambil seluruh data di baris pertama dan kedua.

baris pertama index 0 di dimensi pertama. baris kedua index 1 di dimensi pertama.

kolom mau kita ambil semua, index kolom adalah `:` di dimensi kedua.

jadi, kita mau ambil [[0,1],:]

In [ ]:
arr3[[0,1],:]

array([[ 7, 14, 21, 28, 35],
       [42, 49, 56, 63, 70]])

dengan demikian kita berhasil slicing, mengambil data baris 1 dan 2, dan semua kolom.

bagaimana kalau kita mau ambil data kolom ke-3 saja? index kolom ke-3 adalah 2 di dimensi kedua

jadi kita edit index dimensi kedua dari : menjadi 2

In [ ]:
arr3[[0,1], 2]

array([21, 56])

# latihan pendek
diberikan sebuah numpy array 2 dimensi 5 baris 10 kolom

coba indexing untuk mengambil
- data terakhir baris terakhir kolom terakhir
- data pertama baris pertama kolom pertama
- data baris ke-3 dan kolom ke-7

coba slicing untuk mengambil
- data baris terakhir, kolom ke-3 dan kolom ke-5
- data baris pertama, kedua, ketiga dan kolom ke-8
- data beris pertama, kedua, ketiga dan kolom ke 5,6,7




In [ ]:
arr = np.arange(-75,75,3).reshape((5,10))
arr

array([[-75, -72, -69, -66, -63, -60, -57, -54, -51, -48],
       [-45, -42, -39, -36, -33, -30, -27, -24, -21, -18],
       [-15, -12,  -9,  -6,  -3,   0,   3,   6,   9,  12],
       [ 15,  18,  21,  24,  27,  30,  33,  36,  39,  42],
       [ 45,  48,  51,  54,  57,  60,  63,  66,  69,  72]])

In [ ]:
arr[-1,-1]

72

In [ ]:
arr[0,0]

-75

In [ ]:
arr[2,6]

3

In [ ]:
arr[-1, [2,4]]

array([51, 57])

In [ ]:
arr[[0,1,2], 7]

array([-54, -24,   6])

In [ ]:
arr

array([[-75, -72, -69, -66, -63, -60, -57, -54, -51, -48],
       [-45, -42, -39, -36, -33, -30, -27, -24, -21, -18],
       [-15, -12,  -9,  -6,  -3,   0,   3,   6,   9,  12],
       [ 15,  18,  21,  24,  27,  30,  33,  36,  39,  42],
       [ 45,  48,  51,  54,  57,  60,  63,  66,  69,  72]])

In [ ]:
# data beris pertama, kedua, ketiga dan kolom ke 5,6,7
arr[[0,1,2], [4,5,6]]

array([-63, -30,   3])

In [ ]:
arr[0:3, 4:7]

array([[-63, -60, -57],
       [-33, -30, -27],
       [ -3,   0,   3]])

## teknik edit array lainnya
splitting - memotong array menjadi beberapa bagian yang sama size nya

stacking - menempelkan array, dengan catatan bentuknya harus sama. misal stack rows, jumlah column setiap array yang di stack harus sama.

copy - membuat copy dari array

In [ ]:
arr

array([[-75, -72, -69, -66, -63, -60, -57, -54, -51, -48],
       [-45, -42, -39, -36, -33, -30, -27, -24, -21, -18],
       [-15, -12,  -9,  -6,  -3,   0,   3,   6,   9,  12],
       [ 15,  18,  21,  24,  27,  30,  33,  36,  39,  42],
       [ 45,  48,  51,  54,  57,  60,  63,  66,  69,  72]])

In [ ]:
np.hsplit(arr, 5)

[array([[-75, -72],
        [-45, -42],
        [-15, -12],
        [ 15,  18],
        [ 45,  48]]),
 array([[-69, -66],
        [-39, -36],
        [ -9,  -6],
        [ 21,  24],
        [ 51,  54]]),
 array([[-63, -60],
        [-33, -30],
        [ -3,   0],
        [ 27,  30],
        [ 57,  60]]),
 array([[-57, -54],
        [-27, -24],
        [  3,   6],
        [ 33,  36],
        [ 63,  66]]),
 array([[-51, -48],
        [-21, -18],
        [  9,  12],
        [ 39,  42],
        [ 69,  72]])]

hsplit membagi array kita menjadi beberapa array. di contoh diatas, kita minta 5 array, dipotong dari array awal secara kolom. ada 10 kolom dibagi 5, jadi masing-masing array baru punya 2 kolom

In [ ]:
arr2 = arr.reshape((10,5))
arr2

array([[-75, -72, -69, -66, -63],
       [-60, -57, -54, -51, -48],
       [-45, -42, -39, -36, -33],
       [-30, -27, -24, -21, -18],
       [-15, -12,  -9,  -6,  -3],
       [  0,   3,   6,   9,  12],
       [ 15,  18,  21,  24,  27],
       [ 30,  33,  36,  39,  42],
       [ 45,  48,  51,  54,  57],
       [ 60,  63,  66,  69,  72]])

In [ ]:
np.vsplit(arr2, 5)

[array([[-75, -72, -69, -66, -63],
        [-60, -57, -54, -51, -48]]),
 array([[-45, -42, -39, -36, -33],
        [-30, -27, -24, -21, -18]]),
 array([[-15, -12,  -9,  -6,  -3],
        [  0,   3,   6,   9,  12]]),
 array([[15, 18, 21, 24, 27],
        [30, 33, 36, 39, 42]]),
 array([[45, 48, 51, 54, 57],
        [60, 63, 66, 69, 72]])]

di contoh diatas, kita gunakan vsplit, kita bari array awal menjadi beberapa array baru dari jumlah rows nya. awalnya 10 rows menjadi 5 array masing-masing 2 row. 10 bagi 5 jadi 2.

berikutnya contoh `hstack` menempelkan beberapa array yang jumlah rows nya sama

In [ ]:
a = np.ones((3,2))
b = np.zeros((3,1))

a

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
b

array([[0.],
       [0.],
       [0.]])

In [ ]:
c = np.hstack([a,b])
c

array([[1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 0.]])

berikutnya contoh `vstack` menempelkan beberapa array yang jumlah columns nya sama

In [ ]:
a = np.ones((3,4))
b = np.zeros((2,4))

a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
c = np.vstack([a,b])
c

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

teknik copy kita gunakan untuk membuat copy sebuah array

In [ ]:
arr3

array([[  7,  14,  21,  28,  35],
       [ 42,  49,  56,  63,  70],
       [ 77,  84,  91,  98, 105]])

In [ ]:
arr3_copy = arr3.copy()
arr3_copy

array([[  7,  14,  21,  28,  35],
       [ 42,  49,  56,  63,  70],
       [ 77,  84,  91,  98, 105]])

dengan menggunakan `copy` kita membuat sebuah *deep copy* dimana mengubah arr3_copy hasil copyan tidak mengganggu data awal kita arr3

In [ ]:
# ubah arr3_copy
arr3_copy[-1,-1] = 100
arr3_copy

array([[  7,  14,  21,  28,  35],
       [ 42,  49,  56,  63,  70],
       [ 77,  84,  91,  98, 100]])

In [ ]:
# tidak mengubah array awal kita arr3
arr3

array([[  7,  14,  21,  28,  35],
       [ 42,  49,  56,  63,  70],
       [ 77,  84,  91,  98, 105]])

kalau kita gunakan `view` maka hasil copy dan array asli mengganggu satu sama lain

In [ ]:
arr3_view = arr3.view()
arr3_view

array([[  7,  14,  21,  28,  35],
       [ 42,  49,  56,  63,  70],
       [ 77,  84,  91,  98, 105]])

In [ ]:
arr3_view[-1,-1] = 0

In [ ]:
arr3_view

array([[ 7, 14, 21, 28, 35],
       [42, 49, 56, 63, 70],
       [77, 84, 91, 98,  0]])

In [ ]:
arr3

array([[ 7, 14, 21, 28, 35],
       [42, 49, 56, 63, 70],
       [77, 84, 91, 98,  0]])

mengubah array awal akan mengubah view, begitu pula sebaliknya

# Basic Array Operations
kali bagi tambah kurang

kita bisa lakukan operasi matematik ke array numpy kita

In [ ]:
arr3

array([[ 7, 14, 21, 28, 35],
       [42, 49, 56, 63, 70],
       [77, 84, 91, 98,  0]])

In [ ]:
arr3.shape

(3, 5)

In [ ]:
arr3 + 100

array([[107, 114, 121, 128, 135],
       [142, 149, 156, 163, 170],
       [177, 184, 191, 198, 100]])

In [ ]:
arr3 * 2

array([[ 14,  28,  42,  56,  70],
       [ 84,  98, 112, 126, 140],
       [154, 168, 182, 196,   0]])

In [ ]:
arr4 = np.arange(15).reshape((3,5))
arr4

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
arr3

array([[ 7, 14, 21, 28, 35],
       [42, 49, 56, 63, 70],
       [77, 84, 91, 98,  0]])

In [ ]:
arr3 - arr4

array([[  7,  13,  19,  25,  31],
       [ 37,  43,  49,  55,  61],
       [ 67,  73,  79,  85, -14]])

In [ ]:
arr3 - arr4 + 3 * 2 - 10 / 5

array([[ 11.,  17.,  23.,  29.,  35.],
       [ 41.,  47.,  53.,  59.,  65.],
       [ 71.,  77.,  83.,  89., -10.]])

## Aggregation
selain basic math operations kita bisa minta angka angka hasil agregasi seperti
- max
- min
- sum
- mean (rata rata)
- dan lainnya

In [ ]:
arr

array([[-75, -72, -69, -66, -63, -60, -57, -54, -51, -48],
       [-45, -42, -39, -36, -33, -30, -27, -24, -21, -18],
       [-15, -12,  -9,  -6,  -3,   0,   3,   6,   9,  12],
       [ 15,  18,  21,  24,  27,  30,  33,  36,  39,  42],
       [ 45,  48,  51,  54,  57,  60,  63,  66,  69,  72]])

In [ ]:
arr.max()

72

In [ ]:
arr.min()

-75

In [ ]:
arr.sum()

-75

In [ ]:
arr.mean()

-1.5

# Matrices
nama teknikal untuk numpy array 2 dimensi adalah Matriks, atau di bahasa inggris Matrice, dan kalau banyak jadi Matrices

jika kita mention matrix atau matrice, kita bisa langsung asumsi, numpy array 2 dimensi.

## Dot Product
dot product adalah teknik perkalian antara dua matrix yang sedikit berbeda daripada perkalian antara 2 numpy array a * b.

di perkalian antara 2 numpy array biasa a * b, bentuk shape kedua numpy array harus sama.

kalau di dot product, yang harus sama adalah jumlah kolom di matrix pertama dengan jumlah rows di matrix kedua

kita coba mengerti dengan mengerjakan study case:
- https://docs.google.com/spreadsheets/d/1mD05ghLxEfEGnAhaMy4GuIX3WWwI5bhsQ7krSFlQLbM/edit?usp=sharing
- https://www.mathsisfun.com/algebra/matrix-multiplying.html

Dari data penjualan roti, dan harga jual roti, berapa total penjualan per roti per hari?

kita bisa temukan dengan teknik dot product

In [ ]:
penjualan = np.array([[15,12,21,11],
                      [12,17,7,3],
                      [24,30,45,57],
                      ])
penjualan

array([[15, 12, 21, 11],
       [12, 17,  7,  3],
       [24, 30, 45, 57]])

In [ ]:
harga = np.array([[10000,12000,5000],
                  [3000,5000,1000],
                  [7000,7000,4000],
                ])
harga

array([[10000, 12000,  5000],
       [ 3000,  5000,  1000],
       [ 7000,  7000,  4000]])

In [ ]:
harga.dot(penjualan)

array([[414000, 474000, 519000, 431000],
       [129000, 151000, 143000, 105000],
       [285000, 323000, 376000, 326000]])

baris pertama adalah total penjualan per hari

baris kedua total harga beli

baris ketiga total keuntungan

kita bisa lanjut dengan teknik agregasi sum atau mean, untuk dapat info total penjualan, total profit, rata2 penjualan/profit


In [ ]:
hasil = harga.dot(penjualan)
hasil.sum(axis=1)

array([1838000,  528000, 1310000])

total penjualan 4 hari adalah 1838000, total pembelian / modal adalah 528000, dan total keuntungan adalah 1310000

## review indexing, slicing
matrix adalah numpy array 2 dimensi, jadi kita bisa lakukan indexing dan slicing seperti sebelumnya. caranya sama.

## reshape vs transpose
reshape mengubah shape sebuah numpy array.

transpose juga mengubah dan dia sambil mengingat teman sebaris/ sekolom, tidak dipisah pisah.

reshape tidak ingat teman sebaris/ sekolom, semua angka di urutkan saja kiri ke kanan atas ke bawah.


In [ ]:
a = np.random.random(24)*100
a = a.astype(int).reshape((4, 6))
a

array([[78, 45,  3, 61, 71, 95],
       [75, 18, 97, 21, 64, 45],
       [54, 96, 36, 39, 70,  0],
       [69, 46, 81, 10, 54, 13]])

In [ ]:
# indexing mengambil 1 item. misalnya item di baris ke-3 dan kolom ke-5
a[2,4]

70

In [ ]:
# slicing mengambil beberapa item sekaligus. misalnya 2 baris pertama dan 2 kolom terakhir. index 0,1 dan -2,-1
a[:2, -2:]

array([[71, 95],
       [64, 45]])

In [ ]:
# transpose, teman sebaris akan jadi teman sekolom
# transpose, teman sekolom akan jadi teman sebaris
a.T

array([[78, 75, 54, 69],
       [45, 18, 96, 46],
       [ 3, 97, 36, 81],
       [61, 21, 39, 10],
       [71, 64, 70, 54],
       [95, 45,  0, 13]])

In [ ]:
# reshape tidak ingat teman duduk sebelumnya
a.reshape((6,4))

array([[78, 45,  3, 61],
       [71, 95, 75, 18],
       [97, 21, 64, 45],
       [54, 96, 36, 39],
       [70,  0, 69, 46],
       [81, 10, 54, 13]])